name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd payments && npm install && npm run test:ci
      - run: cd payments && docker build -t dynamicq/payments . 
      - 
        uses: docker/login-action@v1 
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
                 
      - run: docker push dynamicq/payments