name: tests-orders

on:
  pull_request:
    paths:
      - 'orders/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd orders && npm install && npm run test:ci
      
      - run: cd orders && docker build -t dynamicq/orders . 
      - run: 
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        env:
          $DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          $DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push dynamicq/orders 
