name: tests-tickets

on:
  pull_request:
    paths:
      - 'tickets/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd tickets && npm install && npm run test:ci
      - run: cd tickets && docker build -t dynamicq/tickets .
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker push dynamicq/tickets
